Repository MystenLabs/narwhal, pull requests merged in 2022-04, with the labels that each got.

#141 fix: tests in retrieving multiple blocks fail randomly
  primary/src/tests/block_waiter_tests.rs
  primary/src/tests/common.rs
Labels: bug

#136 Always output tx
  Cargo.toml
  crypto/src/ed25519.rs
  executor/Cargo.toml
  executor/src/batch_loader.rs
  executor/src/core.rs
  executor/src/errors.rs
  executor/src/lib.rs
  executor/src/state.rs
  executor/src/subscriber.rs
  executor/src/tests/execution_state.rs
  executor/src/tests/executor_tests.rs
  executor/src/tests/fixtures.rs
  executor/src/tests/sequencer.rs
  executor/src/tests/subscriber_tests.rs
  node/Cargo.toml
  node/src/lib.rs
  node/src/main.rs
Labels: enhancement, good first issue, sui

#158 Do not sync empty parents
  primary/src/header_waiter.rs
Labels: bug

#172 Expose network config
  config/src/lib.rs
Labels: enhancement, good first issue, sui

#185 Output the entire tx data
  consensus/src/tusk.rs
  executor/src/core.rs
  executor/src/lib.rs
  node/src/lib.rs
  node/src/main.rs
Labels: sui

#189 Fix seq number bug
  consensus/src/subscriber.rs
  consensus/src/tests/subscriber_tests.rs
  consensus/src/tusk.rs
  executor/src/batch_loader.rs
  executor/src/core.rs
  executor/src/lib.rs
  executor/src/tests/execution_state.rs
  node/src/lib.rs
  node/src/main.rs
  worker/src/worker.rs
Labels: bug
